version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    container_name: task-manager-php
    depends_on:
      - db
    networks:
      - task_manager_network

  db:
    image: mysql:8.0
    container_name: task-manager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - task_manager_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task-manager-phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - task_manager_network

volumes:
  db_data:

networks:
  task_manager_network:
    driver: bridge
